# Generated by Django 4.2.3 on 2023-08-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="all_topic",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="transcription",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
